import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/home.module.sass'
import Header from '@/components/Header'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CEComp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <div className={styles.banner}>
        <h1>Bem vindo ao CEComp!</h1>
        <h2>Como podemos te ajudar?</h2>
        <nav>
          <ul>
            <li>
              <Link href="#">
                Notícias
              </Link>
            </li>
            <li>
              <Link href="#">
                Serviços
              </Link>
            </li>
            <li>
              <Link href="#">
                Loja
              </Link>
            </li>
          </ul>
          <Link href="#">
            O que é o CEComp
          </Link>
        </nav>
      </div>
      <div className={styles.notices}>
        <h2>Notícias</h2>
        <div className={styles.content}>
          <ul>
            <li>
              <h3>Notícia 1</h3>
              <p>O Naruto pode ser um pouco duro às vezes, talvez você não saiba disso, mas o Naruto também cresceu sem pai. Na verdade ele nunca conheceu nenhum de seus pais, e nunca teve nenhum amigo em nossa aldeia. Mesmo assim eu nunca vi ele chorar, ficar zangado ou se dar por vencido, ele está sempre disposto a melhorar, ele quer ser respeitado, é o sonho dele e o Naruto daria a vida por isso sem hesitar. Meu palpite é que ele se cansou de chorar e decidiu fazer alguma coisa a respeito!</p>
              <div className={styles.contentImage}>
                <Image alt="" src="/img.png" width={100} height={100}/>
              </div>
            </li>
            <li>
              <h3>Notícia 2</h3>
              <p>O Naruto pode ser um pouco duro às vezes, talvez você não saiba disso, mas o Naruto também cresceu sem pai. Na verdade ele nunca conheceu nenhum de seus pais, e nunca teve nenhum amigo em nossa aldeia. Mesmo assim eu nunca vi ele chorar, ficar zangado ou se dar por vencido, ele está sempre disposto a melhorar, ele quer ser respeitado, é o sonho dele e o Naruto daria a vida por isso sem hesitar. Meu palpite é que ele se cansou de chorar e decidiu fazer alguma coisa a respeito!</p>
              <div className={styles.contentImage}>
                <Image alt="" src="/img.png" width={100} height={100}/>
              </div>
            </li>
            <li>
              <h3>Notícia 3</h3>
              <p>O Naruto pode ser um pouco duro às vezes, talvez você não saiba disso, mas o Naruto também cresceu sem pai. Na verdade ele nunca conheceu nenhum de seus pais, e nunca teve nenhum amigo em nossa aldeia. Mesmo assim eu nunca vi ele chorar, ficar zangado ou se dar por vencido, ele está sempre disposto a melhorar, ele quer ser respeitado, é o sonho dele e o Naruto daria a vida por isso sem hesitar. Meu palpite é que ele se cansou de chorar e decidiu fazer alguma coisa a respeito!</p>
              <div className={styles.contentImage}>
                <Image alt="" src="/img.png" width={100} height={100}/>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div className={styles.services}>
        <h2>Serviços</h2>
        <div className={styles.content}>
          <h3>Para todos</h3>
          <ul>
            <li>
              <Link href="#">Calendário de eventos</Link>
            </li>
            <li>
              <Link href="#">Contato</Link>
            </li>
            <li>
              <Link href="#">Loja</Link>
            </li>
            <li>
              <Link href="#">Meus certificados</Link>
            </li>
            <li>
              <Link href="#">Sobre nós</Link>
            </li>
          </ul>
          <h3>Para membros do BCC</h3>
            <ul>
              <li><Link href="#">Transparência</Link></li>
              <li><Link href="#">Votações</Link></li>
            </ul>
        </div>    
        <footer>
            <h3>Centro Estudantil da Ciência da Computação</h3>
            <h3>USP Ribeirão Preto</h3>
            <h3>XX.XXX.XXX/YYYY-ZZ</h3>
        </footer>
      </div>
 
    </div>
  )
}
